version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studybuddy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  create-bucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: ["/bin/sh","-c"]
    command: >
      "mc alias set local http://minio:9000 minioadmin minioadmin &&
       mc mb -p local/studybuddy || true"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      APP_URL: http://localhost:5173
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/studybuddy
      REDIS_URL: redis://redis:6379/0
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET: studybuddy
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_MODEL: mistral
      OLLAMA_OCR_MODEL: mistral-ocr-2503
      OCR_ENGINE: tesseract
      OCR_MAX_PAGES: 20
    depends_on:
      - db
      - redis
      - minio
      - create-bucket
      - ollama
    ports:
      - "8000:8000"
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000","--reload"]

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/studybuddy
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: minioadmin
      S3_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET: studybuddy
      OLLAMA_HOST: http://ollama:11434
      OLLAMA_OCR_MODEL: mistral-ocr-2503
      OCR_ENGINE: tesseract
      OCR_MAX_PAGES: 20
    depends_on:
      - redis
    command: ["celery","-A","app.tasks.worker.celery_app","worker","-l","info"]

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  minio_data:
  ollama:
